name: Alpine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Run
        id: version
        run: |
          apk update
          echo ::set-output name=JQ_VERSION::$(apk search -x jq)
      - name: Run2
        run: |
          echo $JQ_VERSION
        env:
          JQ_VERSION: ${{ steps.version.outputs.JQ_VERSION }}
