name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Save to file
        run: echo Hello, world! > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test_artifact
          path: ./artifact.txt
