name: Version

on:
  workflow_dispatch:

jobs:
          
  build:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Run
        run: |
          apt-get update
          apt-get install -y jq curl
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Retrieve VERSION
        run: |
          set -xe
          VERSION=$(curl -s https://pypi.org/pypi/pyicloud/json | jq --raw-output '.releases | keys | sort_by(. | split(".") | map(tonumber)) | .[-1:][0]')
          if [ -z "$VERSION" ]; then
            echo '$VERSION is empty!'
            exit 1
          fi
          echo $VERSION
